### ISSUE TITLE
Looks like the plugin may be out of date relative to Gradle

### ISSUE THREAD

**Issue by bpappin** [dcendents/android-maven-gradle-plugin#28]
I seem  to be getting an unexpected error from within the plugin.
Looks like the plugin is out of date relative to the grade api.

```

Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:89)
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:55)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
	at org.gradle.api.Project$apply$0.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_8hiypez9k9isie460hnxv7097.run(/Users/bpappin/Workspace/conx2share-android/app/build.gradle:21)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 42 more
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:89)
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:55)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
	at org.gradle.api.Project$apply$0.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_8hiypez9k9isie460hnxv7097.run(/Users/bpappin/Workspace/conx2share-android/app/build.gradle:21)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 42 more
```

**Comment by dcendents** [comment]
I have tested the latest version (1.3) with gradle 2.6 without any problems.
Can you tell me which version of the plugin you are using and what version of gradle?

The following table shows the compatibility matrix:

| Plugin Version | Plugin Name | Gradle Version |
| ------------- | ----------- | ----------- |
| 1.0 | android-maven | 1.8+ |
| 1.1 | android-maven | 1.12+ |
| 1.2 | com.github.dcendents.android-maven | 2.2+ |
| 1.3 | com.github.dcendents.android-maven | 2.4+ |

Please note that version 1.0 to 1.2 were released under the artifactId android-maven-plugin

**Comment by bpappin** [comment]
I'm getting the same error in the latest version of android studio.

./gradlew --version

------------------------------------------------------------
Gradle 2.2.1
------------------------------------------------------------

Build time:   2014-11-24 09:45:35 UTC
Build number: none
Revision:     6fcb59c06f43a4e6b1bcb401f7686a8601a1fb4a

Groovy:       2.3.6
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.10.5 x86_64

```java
Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.project.ProjectInternal.getPluginManager()Lorg/gradle/api/internal/plugins/PluginManagerInternal;
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:89)
	at org.gradle.api.plugins.AndroidMavenPlugin.apply(AndroidMavenPlugin.java:55)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.providePlugin(DefaultPluginContainer.java:188)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.addPluginInternal(DefaultPluginContainer.java:137)
	at org.gradle.api.internal.plugins.DefaultPluginContainer.apply(DefaultPluginContainer.java:103)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyPlugin(DefaultObjectConfigurationAction.java:115)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:131)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:37)
	at org.gradle.api.Project$apply$0.call(Unknown Source)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.groovy:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_3yt0uvbm5hjlobfmjmrolmt5g.run(/Users/bpappin/Workspace/conx2share-android/mopub-sdk/build.gradle:29)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:52)
	... 78 more

```

**Comment by jeanregisser** [comment]
@bpappin I had the same issue. I fixed it by upgrading gradle.

Edit the `gradle/wrapper/gradle-wrapper.properties` file so that it references the latest version:

```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-2.6-all.zip
...
```

**Comment by sabiransari41** [comment]
After Adding 
distributionUrl=https\://services.gradle.org/distributions/gradle-2.6-all.zip
i am getting
Unsupported method: BaseConfig.getApplicationIdSuffix().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Comment by segin** [comment]
@sabir41 look here: https://stackoverflow.com/questions/44546849/unsupported-method-baseconfig-getapplicationidsuffix
